### ISSUE TITLE
Unit Test Nextflow Functions

### ISSUE THREAD

**Issue by aaron-fishman-achillestx** [askimed/nf-test#16]
It would be great to be able to unit test nextflow functions in a similar way to processes/workflows. In addition to return values, the stdout/stderr could be captured and compared. For example:

### functions.nf
```
def say_hello(name) {
    if (name == null) {
        error('Cannot greet a null person')
    }
        
    def greeting = "Hello ${name}"

    println(greeting)
    return greeting
}
```

### functions.nf.test
```
nextflow_function {

  name "Test Function Say Hello"

  script "example/functions.nf"
  function "say_hello"

  test("Passing case") {

    when {
      function {
        """
        input[0] = "aaron"
        """
      }
    }

    then {
      assert function.success
      assert function.return == "Hello aaron"
      assert function.stdout == "Hello aaron"
      assert function.stderr == ""
    }

  }

  test("Failure Case") {

    when {
      function {
        """
        input[0] = null
        """
      }
    }

    then {
      assert process.failed
      assert function.stderr.contains("Cannot greet a null person")
    }
  }
}
```

**Comment by lukfor** [comment]
Hey Aaron,

Thanks for your great concept! The outlined functionality fits perfectly into nf-test and I think it's super helpful :)
I had to change only two things from your proposal:
- Rename `function.return` to `function.result`, since `return` is defined as a keyword.
- It seems to me, that the `error(..)` functions print the error messages to stdout and not stderr.
 
Three scenarios are now possible:

1) Nextflow file including exactly 1 function
```Groovy
nextflow_function {
    name "<NAME>"
    script "<PATH/TO/NEXTFLOW_SCRIPT.nf>"
    function "<FUNCTION_NAME>"
    test("<TEST_NAME>") {
    }
}
```

2) Nextflow file including several functions
Until now, a *.nf.test file for each function is required. If you have a huge library with several functions, this could be very confusing. Therefore, I added the possibility that the global defined function name can be overwritten in each test.
Somehting like this:
```Groovy
test("<TEST_NAME>") {
    function: "<FUNCTION_NAME>"
    when {
      ...
    }
    then {
     ...
    }
}
```

3) Skip `script` property
You can also skip the `script` property: This enables testing functions from groovy files that are in the `lib` folder and therefore already in the classpath.

By default, the `nf-test generate function` sub-command reads a *.nf file and creates a testsuite with one testcase per function.

---

Please see here for a running example using the latest version from the branch:
**`pipeline.nf`**
```Groovy
def mult(a, b) {
  return a*b
}
def div(a, b) {
  return a/b
}
```

**`pipeline.nf.test`**

```Groovy
nextflow_function {
  name "Test Pipeline with 1 process"
  script "pipeline.nf"
  test("Test multiplication") {
    function "mult"
    when {
      function {
      """
      input[0] = 3
      input[1] = 4
      """
      }
    }
    then {
      assert function.success
      assert function.result == 12
    }
  }
  test("Test division") {
    function "div"
    when {
      function {
      """
      input[0] = 6
      input[1] = 2
      """
      }
    }
    then {
      assert function.success
      assert function.result == 3
    }
  }
}
```

----

I created a pull request with this new features: #23 . Maybe you can give it a try before we merge that back into the main branch?

Thanks again for your help!

**Comment by lukfor** [comment]
And here a working version of your example:

**`functions.nf`**

```Groovy
def say_hello(name) {
    if (name == null) {
        error('Cannot greet a null person')
    }

    def greeting = "Hello ${name}"

    println(greeting)
    return greeting
}
```

**`functions.nf.test`**

```Groovy
nextflow_function {

  name "Test Function Say Hello"

  script "functions.nf"
  function "say_hello"

  test("Passing case") {

    when {
      function {
        """
        input[0] = "aaron"
        """
      }
    }

    then {
      assert function.success
      assert function.result == "Hello aaron"
      assert function.stdout.contains("Hello aaron")
      assert function.stderr == []
    }

  }

  test("Failure Case") {

    when {
      function {
        """
        input[0] = null
        """
      }
    }

    then {
      assert function.failed
      //It seems to me that error(..) writes message to stdout
      assert function.stdout.contains("Cannot greet a null person")
    }
  }
}
```

**Comment by aaron-fishman-achillestx** [comment]
Very cool! Just provided some comments for the PR. Odd that error does not write to stdout. I think Khushbu (our QA lead) is doing a bit more testing with this as well and will feedback on bugs if she finds.
