### ISSUE TITLE
JUnit Output

### ISSUE THREAD

**Issue by aaron-fishman-achillestx** [askimed/nf-test#21]
Would be really great if it was possible to optionally output test results in [xunit](https://xunit.net/docs/format-xml-v2) format - as this would make interfacing with reporting in CI systems, (eg bitbucket) easier. 

For example, it could run: `nf-test test --xunit test_results.xml example/*.nf.test `

**Comment by aaron-fishman-achillestx** [comment]
Hey @lukfor  / @seppinho ,

We've realised it's really JUnit XML output we need (rather than xunit). We're now looking into generating JUnit xml data instead (possibly using the JUnit package or otherwise). If there are any specific packages you'd recommend for this, let me know!

Seems like JUnit xml is a standard format that CI systems often use, so perhaps it will also be valuable for others in the community as well.

**Comment by lukfor** [comment]
We are using [`tap4j` ](https://github.com/tupilabs/tap4j)to create the TAP output. The class `TapProducerFactory` provides also a [JUnit producer](https://tap4j.sourceforge.net/apidocs/org/tap4j/producer/TapProducerFactory.html). This would be the easiest way, because the code from [TapTestReportWriter](https://github.com/askimed/nf-test/blob/main/src/main/java/com/askimed/nf/test/core/reports/TapTestReportWriter.java) could be reused.

However, I am not sure if this implementation take advantage of all JUnit attributes. Otherwise you could use [`TapJunitRepresenter`](https://github.com/tupilabs/tap4j/blob/master/src/main/java/org/tap4j/representer/TapJunitRepresenter.java) as a start point for your own implementation.

**Comment by aaron-fishman-achillestx** [comment]
Hey @lukfor , 

Just made a PR for this feature! We opted for using the core java XML writing utilities for implementation. Look forward to your feedback.

**Comment by lukfor** [comment]
Thank you @aaron-fishman-achillestx and @byb121!
