### ISSUE TITLE
Feature request - Order-agnostic JSON/YAML object comparison

### ISSUE THREAD

**Issue by ivopieniak** [askimed/nf-test#32]
Hi,

Thanks for developing the nf-test. It has a great potential to be a go-to tool for the whole Nextflow community.

It would be great if we could add an ability to JSON/YAML object comparison with included support of gzipped files. I believe nf-core and Nextflow people do try to push for using JSON a lot with configs etc. It could super useful to have this easy ability to compare JSON files here. 

I believe this package could be helpful? - https://github.com/skyscreamer/JSONassert

**Comment by ivopieniak** [comment]
Hi @lukfor, 

Me, @aaron-fishman-achillestx @byb121 were thinking of implementing this feature as the next one during our hackathon. One thing that caught our attention was that, we would potentially abstract the code that has been used in the FASTA comparison plugin in order to maintain similar syntax. Therefore, we have a couple of questions:
1) Should we be writing this feature as a part of the core nf-test or as a plugin?
2) If this would be desired as the core functionality, would you be able to recommend us a location within the package where this would need to be implemented as well as any other tips that we could leverage?

**Comment by lukfor** [comment]
Cool! Thanks for the support! :+1: I think this is a core functionality and should be part of nf-test.

I would recommend the following approach:

(1) Adapt the existing `json` method of [`PathExtension`](https://github.com/askimed/nf-test/blob/main/src/main/java/com/askimed/nf/test/lang/extensions/PathExtension.java) to return a `JsonFile` instead of `Map`:

```Java
class PathExtension {
	...
	
  /* JSON */

	public static JsonFile readJSON(Path self) throws FileNotFoundException, IOException {
		return new JsonFile(self);
	}

	public static JsonFile getJson(Path self) throws FileNotFoundException, IOException {
		return new JsonFile(self);
	}

	...

}

```


(2) Implement the class `JsonFile` as a `Map` extension (to be compatible with the current implementation) and overwrite the `compareTo` method to use `JSONAssert.assertEquals(...)` from your suggested library.

```Java
public class JsonFile extends HashMap<String, Object> implements Comparable<JsonFile>{
 		
	public JsonFile(Path path) throws IOException {
		JsonSlurper jsonSlurper = new JsonSlurper();
		Map<String, Object> map = (Map<String, Object>) jsonSlurper.parse(path);
		this.putAll(map);	
	}
	
		
	@Override
	public int compareTo(JsonFile other) {
		
		JSONObject object = new JSONObject(this);
		JSONObject otherObject = new JSONObject(other);

		// TODO: check parameters
		// I think assertEquals throws an exception when not the same objects. nf-test uses that exception as error message.
		JSONAssert.assertEquals(object, otherObject, ...);

		//assert was successful --> same objects --> return 0.
		return 0;

	}
	
}
```

(3) You can then use the `json` property in combination with the `==` operator (the `compareTo(..)` method is used to check if they are the same):

```
assert path("file1.json").json == path("file2.json").json
```

(4) You could add also a static method `public static JsonFile json(String jsonContent){...}` to the class [`GlobalMethods`](https://github.com/askimed/nf-test/blob/main/src/main/java/com/askimed/nf/test/lang/extensions/GlobalMethods.java) that creates a `JsonFile` from the provided json content to enable something like this:


```
then {


  def expected =
  """
  {
    "name": "Lukas",
    "age": "35"
  }
  """

 assert json(expected) == path("file2.json").json

}
```

Or we could think about extending the `String` class by a `json` property to enable this syntax:


```
then {

  def expected =
  """
  {
    "name": "Lukas",
    "age": "35"
  }
  """

 assert expected.json == path("file2.json").json

}
```

Be aware, that these code snippets are untested with possible typos etc.. ;)

Happy to discuss and thanks for your efforts!

Best, Lukas.

**Comment by ivopieniak** [comment]
@lukfor thanks a lot for your snippet! 

We have realised that this functionality is already built in to the JSONslurper. Following line works already pretty well! Unless there's something that we are unaware of, I think that all we need to do is to mention this possibility in the documentation. We are happy to update the docs if you would like :)!
```
assert path('some.json').json == path('other.json'). json 
```

Additionally, we will go ahead and extend the implementation for YAMLslurper. Let us know, if you have other preferences for this. 

Iwo, Aaron and Yaobo

**Comment by lukfor** [comment]
> We are happy to update the docs if you would like :)!

Thanks, that would be great! 

> Additionally, we will go ahead and extend the implementation for YAMLslurper. Let us know, if you have other preferences for this.

Perfect! Thank you guys!
