### ISSUE TITLE
Bug report: `nf-test` stops at first failure

### ISSUE THREAD

**Issue by nvnieuwk** [askimed/nf-test#43]
Hi, 

The output of `nf-test` only show the first assertion failure even if there are multiple assertion failures. It would be really helpful and a time saver if the output would show all assertion failures at once. I hope this won't be too hard to implement.

Cheers,
Nicolas

**Comment by aaron-fishman-achillestx** [comment]
Hey @nvnieuwk ,

Your suggestion is akin to [JUnit's assertAll ](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertAll-org.junit.jupiter.api.function.Executable...-). Here is a [StakeOverflow example](https://stackoverflow.com/questions/40796756/assertall-vs-multiple-assertions-in-junit5) as well. 

It doesn't look like groovy has an assertAll out of the box. Fairly simple to implement though (see below). @lukfor  if you and @nvnieuwk  like this, can try to integrate this into nf-test so it is available out-of-the-box. A Java implementation is also possible if that retrofits easier:

` assertAll.groovy `
``` groovy
def assertAll (Closure... closures) {
	// Asserts that all supplied closures do not throw exceptions.
	// The number of failed closures is reported in the Exception message
	int failed = 0

	for (closure in closures) {
		try {
			closure()
		}
		catch (Throwable e) {
			failed++
			println e
		}
	}

	if (failed) {
		throw new Exception("$failed of ${closures.size()} assertions failed")
	}
}


// Example
a = 2

assertAll(
	{ assert a==1 },
	{ a = 1/0 },
	{ assert a==2 },
	{ assert a==3 }
)
```

Produces:
```
$ groovy assertAll.groovy 
Assertion failed: 

assert a==1
       ||
       |false
       2

java.lang.ArithmeticException: Division by zero
Assertion failed: 

assert a==3
       ||
       |false
       2

Caught: java.lang.Exception: 3 of 4 assertions failed
java.lang.Exception: 3 of 4 assertions failed
	at assertAll.assertAll(assertAll.groovy:19)
	at assertAll.run(assertAll.groovy:27)
```

**Comment by nvnieuwk** [comment]
That would be an awesome addition! Good to know it's not that difficult to implement :rocket: . Could it also be possible to maybe let `nf-test` do this by default without having to add an extra line of code?

**Comment by aaron-fishman-achillestx** [comment]
Cheers! I think that might be more difficult, as we would have to figure out how to resume a failed execution, or redefine the assert method to log the error instead of throwing. I'm unsure about this this sort of behaviour, as this isn't how groovy or java does it. My instinct is to align with existing testing design patterns here.

@lukfor what do you think?

**Comment by lukfor** [comment]
Thanks @aaron-fishman-achillestx, cool idea! Your `assertAll` suggestion fits perfect with the nf-test concept, because I would also avoid to change the behaviour of the existing `assert` method. 

It would be great if you could try to implement this feature by translating the code to java and adding it as static method to the class [`GlobalMethods`](https://github.com/askimed/nf-test/blob/main/src/main/java/com/askimed/nf/test/lang/extensions/GlobalMethods.java). 👍
